spring.application.name=Api-Gateway
server.port=9090
#Discovery Server address
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true


# Connection Timeout (milliseconds)
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=1000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=5s


#actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoint.gateway.access=read_only
#management.endpoint.health.show-details=always

info.app.name=Api-Gateway
info.app.description=This is API Gateway common entry point.
info.app.version=1.0

#Resiliance4j circuitBreaker configuration
# Default Circuit Breaker Config for all services
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true

#RateLimiter configurations
spring.data.redis.host=localhost
spring.data.redis.port=6379


#java configuration methods for routes
#define our routes
#spring.cloud.gateway.server.webflux.routes[0].id=food-service
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://FOOD-SERVICE
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/foods/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/foods/?(?<remaining>.*), /$\{remaining}
#
#spring.cloud.gateway.server.webflux.routes[1].id=restaurant-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://RESTAURANT-SERVICE
#spri ng.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/restaurant/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/restaurant/?(?<remaining>.*), /$\{remaining}
