server:
  port: 9092

spring:
  application:
    name: food-service
  datasource:
    url: jdbc:mysql://localhost:3307/Food_Service_DB?createDatabaseIfNotExist=true
    username: root
    password: Vijay

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
