spring.application.name=food-service

#set into environment
spring.profiles.active=dev

#hamko configuration kaha se import kerni hai
spring.config.import=optional:configserver:http://localhost:9092/


