spring.application.name=Config-Server
server.port=9092


#Github location where our configurations is store
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/Vijay-kumar10/Foodie-Microservice-configurations.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=5
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

#endpoint of eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#manamement properties
management.info.env.enabled=true
management.endpoints.web.exposure.include=*

#actuator/info configuraiton
info.app.name=Config-server
info.app.description=This is Config server that store all the properties files of others applications.
info.app.version=1.0 Implemented

#Encription key for github
encrypt.key=42j5jkjen898$%$^%^RBhjbjgjgj6596525625&^&*bhjbUY