server.port=8400




#database configuraiton
spring.datasource.url=jdbc:mysql://localhost:3307/Food_Service_DB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vijay

#jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#actuator/info configuraiton
info.app.name=Food-Service-Production
info.app.description=This application is ready for users in production and configurations occur from config Server.
info.app.version=1.0 Under-Production


