spring.application.name=restaurant-service

#set into environment
spring.profiles.active=dev

#hamko configuration kaha se import kerni hai
spring.config.import=optional:configserver:http://localhost:9092/

#Rabbit-MQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest